steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/quick-cacao-370017/cra-clud-run', '-f', './Dockerfile.dev', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/quick-cacao-370017/cra-clud-run']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'petalog-client'
      - '--image'
      - 'gcr.io/quick-cacao-370017/cra-clud-run'
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'
images:
  - 'gcr.io/quick-cacao-370017/cra-clud-run'
