name: Cloud Run Deploy workflow in develop branch

on:
  push:
    branches:
      - 'develop'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    name: GCP Cloud Run Deploy job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/196067262552/locations/global/workloadIdentityPools/petalog-workload-pool/providers/petalog-provider' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' # e.g. - my-service-account@my-project.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Deploy
        run: gcloud builds submit --config ./cloudbuild.dev.yml .
